# Generated by Django 3.1.6 on 2021-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('user_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('portExistingNumber', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('sharedDocument', models.FileField(upload_to='')),
            ],
        ),
    ]
